artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_file: artifacts/data_ingestion/stock_data.csv
  ticker: AAPL
  start_date: 2000-01-01
  end_date: 2026-08-04

data_validation:
  root_dir: artifacts/data_validation
  raw_data_file: artifacts/data_ingestion/stock_data.csv
  status_file: artifacts/data_validation/status.txt
  ge_expectation_suite: stock_expectation_suite


data_transformation:
  root_dir: artifacts/data_transformation
  raw_data_file: artifacts/data_ingestion/stock_data.csv
  test_size: 0.2
  target_column: "close"
  date_column: "date"
  



